# Generated by Django 3.1 on 2020-09-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_birth_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='games',
        ),
        migrations.DeleteModel(
            name='ProfileGame',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
