# Generated by Django 3.1 on 2020-09-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20200902_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
