# Generated by Django 3.1 on 2020-09-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_meeting_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='tutor',
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='host',
            field=models.BooleanField(default=False, verbose_name='host'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.DeleteModel(
            name='MeetingPoll',
        ),
    ]
