# Generated by Django 3.1 on 2020-09-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_auto_20200916_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
