# Generated by Django 3.1 on 2020-09-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_auto_20200920_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='host',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active?'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='is public?'),
        ),
    ]
